### ISSUE TITLE
As an event owner I want to send invitations by email so that others users will join my event.

### ISSUE THREAD

**Issue by gponsu** [TheTreeHouse/turniquette-api#14]

**Comment by d2bit** [comment]
@scruti can you read aloud the issue title? Because I feel something is wrong when I do. :stuck_out_tongue_closed_eyes: 
http://amerenglish-grammar-2.webs.com/articles.htm

> - a + singular noun beginning with a consonant: a boy
> - an + singular noun beginning with a vowel: an elephant
> - a + singular noun beginning with a consonant sound: a user (sounds like 'yoo-zer,' i.e. begins with a consonant 'y' sound, so 'a' is used)
> - some + plural noun: some girls

**Comment by d2bit** [comment]
Could any user invite new people? I suggest this new title/user story.

```
As an event owner
I want to send invitations by email
So that others users will join my event.
```

@TheTreeHouse/owners WDYT?

**Comment by scruti** [comment]
I had no idea about the third rule. +1 too the changes.

**Comment by d2bit** [comment]
@Dygerydoo can you design the invitation email?
