### ISSUE TITLE
Introduce continuous integration tool

### ISSUE THREAD

**Issue by gponsu** [TheTreeHouse/turniquette-api#2]

**Comment by d2bit** [comment]
Do you agree to create a `tree-house` gh user to create all the ci hooks?
I think is better than having some of us commenting as codeclimate..
Also I've seen PullReview only allows one free user, so I guess we should share a login email.
More over.. as @gponsu wanted to set some bootstrap commits to other user, it could be this pseudo-real user.
If you agree we need a team email. I'm gonna register `turniquette@gmail.com` as it's available... before anyone stoles it

**Comment by gponsu** [comment]
Test broken because we haven't rails yet. 

I should change the configuration of travis test to pass this PR?

**Comment by scruti** [comment]
:+1:  to @d2bit
