### ISSUE TITLE
the project needs an env variable to work

### ISSUE THREAD

**Issue by jguitar** [TheTreeHouse/turniquette-api#33]
without `MONGODB_SOCKET=localhost:27017` it does not work

**Comment by jguitar** [comment]
I'm trying to add [dotenv](https://github.com/bkeepers/dotenv) but I have to fork it and PR.

**Comment by d2bit** [comment]
I think is best to set localhost if ENV['MONGODB_SOCKET'] does not exist in `mongoid.yml`

**Comment by jguitar** [comment]
I added the gem because Travis works with the `ENV` variable. How are all of you doing with this?

**Comment by gponsu** [comment]
@TheTreeHouse/owners  This PR https://github.com/TheTreeHouse/turniquette-api/pull/37 fixed it, no? This issue can be closed, right?

**Comment by jguitar** [comment]
yes, it's fixed ;)
