### ISSUE TITLE
Introduce code climate or similar

### ISSUE THREAD

**Issue by gponsu** [TheTreeHouse/turniquette-api#4]

**Comment by scruti** [comment]
I like combining CodeClimate and [PullReview](https://www.pullreview.com/)

**Comment by gponsu** [comment]
Perfect, i didn't know pullreview, but i like it!

**Comment by d2bit** [comment]
I've created 2 PR for this. codeclimate #6 & pullreview #7

**Comment by scruti** [comment]
:cool:
